name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

# ESTA SEÇÃO É A CHAVE: Ela dá permissão para o robô criar a branch gh-pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build
        run: npm run build
        working-directory: ./client

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Ajustado para garantir que pegue a pasta dist correta
          publish_dir: ./dist