name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # Ou a versão que você usa localmente

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        # Instalamos na raiz para garantir que o 'shared' e 'client' sejam lidos
        run: pnpm install

      - name: Build
        # O comando de build deve ser disparado de onde o package.json principal está
        # Se o script de build estiver no package.json da raiz:
        run: pnpm run build
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # O seu vite.config.ts manda o build para a pasta /dist na raiz
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'